name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Stage files to public directory
      run: |
        mkdir -p ./frontend/mysite.io/public
        cp {mermaid.min.js,index.html} ./frontend/mysite.io/public
    - name: Stage file to GH Pages
      uses: peaceiris/actions-gh-pages@v2.5.0
      env: 
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./frontend/mysite.io/public
    - name: Take screenshot and add to public directory
      run: |
        curl -X POST \
        https://chrome.browserless.io/screenshot \
        -H 'Cache-Control: no-cache' \
        -H 'Content-Type: application/json' \
        --output thought_flow.png \
        -d '{
        "url": "https://jason-michaels.github.io/thought-flow/",
        "options": {
          "type": "png",
          "quality": 100
          }
        }'
        cp thought_flow.png ./frontend/mysite.io/public
    - name: Add screenshot file to GH Pages
      uses: peaceiris/actions-gh-pages@v2.5.0
      env: 
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./frontend/mysite.io/public
      with:
        keepFiles: true  
